---
kind: pipeline
type: docker
name: default
trigger:
  event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/drone-cache
  - name: poetry
    temp: {}
  - name: poetry-cache
    temp: {}

services:
  - name: redis
    image: redis:6-alpine

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "poetry.lock" }}'
      archive_format: "gzip"
      mount:
        - '.poetry'
        - '.poetry-cache'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install-dependencies
    depends_on: [restore-cache]
    image: python:3.9.1
    commands:
      - |
        export POETRY_HOME=$DRONE_WORKSPACE/.poetry
        export POETRY_CACHE_DIR=$POETRY_HOME/cache
        if [ ! -d "$POETRY_HOME" ]; then
          curl -fsS -o /tmp/install-poetry.py https://install.python-poetry.org
          python /tmp/install-poetry.py -y
        fi
        $POETRY_HOME/bin/poetry install --no-root

  - name: test
    depends_on: [install-dependencies]
    image: python:3.9.1
    environment:
      DJANGO_SETTINGS_MODULE: tests.settings
    commands:
      - . .poetry/cache/virtualenvs/*/bin/activate
      - black . --check
      - isort --check-only .
      - pylint django_toolshed tests
      - pytest --cov=tests --cov=django_toolshed tests django_toolshed
    volumes:
      - name: cache
        path: /tmp/cache

  - name: rebuild-cache
    depends_on: [install-dependencies]
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "poetry.lock" }}'
      archive_format: "gzip"
      mount:
        - '.poetry'
        - '.poetry-cache'
    volumes:
      - name: cache
        path: /tmp/cache
